// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq5up2f5sX5Xt3jq9fuCd556Rae743y4U',
    appId: '1:629336655193:web:7bf6dabd0b21831254b848',
    messagingSenderId: '629336655193',
    projectId: 'orman-3980d',
    authDomain: 'orman-3980d.firebaseapp.com',
    storageBucket: 'orman-3980d.appspot.com',
    measurementId: 'G-3LPHXWY7Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpA4KlaCSrnY7VlzKBh7x7PLwPQtvYedk',
    appId: '1:629336655193:android:18a6b42c8b016bfc54b848',
    messagingSenderId: '629336655193',
    projectId: 'orman-3980d',
    storageBucket: 'orman-3980d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnARi8pmwFS4tH0ag0mpPJFU1lyuijsrg',
    appId: '1:629336655193:ios:6f407642e2005c6b54b848',
    messagingSenderId: '629336655193',
    projectId: 'orman-3980d',
    storageBucket: 'orman-3980d.appspot.com',
    iosBundleId: 'com.example.orman1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnARi8pmwFS4tH0ag0mpPJFU1lyuijsrg',
    appId: '1:629336655193:ios:6f407642e2005c6b54b848',
    messagingSenderId: '629336655193',
    projectId: 'orman-3980d',
    storageBucket: 'orman-3980d.appspot.com',
    iosBundleId: 'com.example.orman1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq5up2f5sX5Xt3jq9fuCd556Rae743y4U',
    appId: '1:629336655193:web:0f55249eace6d7a654b848',
    messagingSenderId: '629336655193',
    projectId: 'orman-3980d',
    authDomain: 'orman-3980d.firebaseapp.com',
    storageBucket: 'orman-3980d.appspot.com',
    measurementId: 'G-1TX96ZGKHC',
  );
}
